# Generated by Django 4.2.4 on 2023-09-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='des',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
